# $OpenBSD$

COMMENT =	tools for authors of OCaml ppx rewriters
CATEGORIES =	devel

V =		0.99.2
GH_ACCOUNT =	alainfrisch
GH_PROJECT =	ppx_tools
GH_TAGNAME =	ppx_tools_${V}
DISTNAME =	${GH_PROJECT}-${GH_TAGNAME}
PKGNAME =	ocaml-ppx-tools-${V}

HOMEPAGE =	https://github.com/${GH_ACCOUNT}/${GH_PROJECT}

# MIT
PERMIT_PACKAGE_CDROM =		Yes

MODULES =	lang/ocaml
USE_GMAKE =	Yes

.include <bsd.port.mk>
